blogging/urls.py
from django.conf.urls import url
from django.urls import path
from blogging.views import stub_view, PostListView, PostDetailView, add_model

urlpatterns = [
    path("", PostListView.as_view(), name="blog_index"),
    path("add/", add_model, name="add_post"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="blog_detail"),
]

mysite/blogging/urls.py
from django.conf.urls import url
from django.urls import path
from blogging.views import stub_view, PostListView, PostDetailView

urlpatterns = [
    path("", PostListView.as_view(), name="blog_index"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="blog_detail"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blogging.urls")),
    path("polling/", include("polling.urls")),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
]

mysite/polling/urls.py
from django.urls import path
from polling.views import PollListView, PollDetailView

urlpatterns = [
    path("", PollListView.as_view(), name="poll_index"),
    path("polls/<int:pk>", PollDetailView.as_view(), name="poll_detail"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogging.urls')),
    path('polling/', include('polling.urls')),
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(next_page='/'), name="logout")
]

polling/urls.py
from django.urls import path
from polling.views import PollListView, PollDetailView

urlpatterns = [
    path('', PollListView.as_view(), name="poll_index"),
    path('polls/<int:pk>', PollDetailView.as_view(), name="poll_detail")
]

blogging/models.py
from django.db import models

from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name="categories")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

mysite/polling/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

polling/models.py
from django.db import models

class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

blogging/forms.py
from django.forms import ModelForm
from blogging.models import Post


class MyPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "text", "author"]

blogging/views.py
from django.http.response import Http404, HttpResponse
from django.shortcuts import render, redirect
from django import forms
from django.utils import timezone
from django.template import loader
from blogging.models import Post
from blogging.forms import MyPostForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


def stub_view(request, *args, **kwargs):
    body = "Stub View\n\n"
    if args:
        body += "Args:\n"
        body += "\n".join(["\t%s" % a for a in args])
    if kwargs:
        body += "Kwargs:\n"
        body += "\n".join(["\t%s: %s" % i for i in kwargs.items()])
    return HttpResponse(body, content_type="text/plain")


def add_model(request):

    if request.method == "POST":
        form = MyPostForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.published_date = timezone.now()
            model_instance.save()
            return redirect("/")
    else:
        form = MyPostForm()
        return render(request, "add.html", {"form": form})


class PostListView(ListView):
    queryset = Post.objects.exclude(published_date__exact=None)
    post_list = queryset.order_by("-published_date")
    template_name = "list.html"


class PostDetailView(DetailView):
    queryset = Post.objects.exclude(published_date__exact=None)
    template_name = "blogging/detail.html"

mysite/blogging/views.py
from django.http.response import Http404, HttpResponse
from django.shortcuts import render
from django.template import loader
from blogging.models import Post
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


def stub_view(request, *args, **kwargs):
    body = "Stub View\n\n"
    if args:
        body += "Args:\n"
        body += "\n".join(["\t%s" % a for a in args])
    if kwargs:
        body += "Kwargs:\n"
        body += "\n".join(["\t%s: %s" % i for i in kwargs.items()])
    return HttpResponse(body, content_type="text/plain")


class PostListView(ListView):
    queryset = Post.objects.exclude(published_date__exact=None)
    post_list = queryset.order_by("-published_date")
    template_name = "list.html"


class PostDetailView(DetailView):
    queryset = Post.objects.exclude(published_date__exact=None)
    template_name = "blogging/detail.html"

mysite/polling/views.py
from django.shortcuts import render
from django.http import Http404
from polling.models import Poll
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


class PollListView(ListView):
    model = Poll
    template_name = "polling/list.html"


class PollDetailView(DetailView):
    model = Poll
    template_name = "polling/detail.html"

    def post(self, request, *args, **kwargs):
        poll = self.get_object()

        if request.POST.get("vote") == "Yes":
            poll.score += 1
        elif request.POST.get("vote") == "No":
            poll.score -= 1
        poll.save()

        context = {"object": poll}
        return render(request, "polling/detail.html", context)

polling/views.py
from django.shortcuts import render
from django.http import Http404
from polling.models import Poll
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


class PollListView(ListView):
    model = Poll
    template_name = 'polling/list.html'


class PollDetailView(DetailView):
    model = Poll
    template_name = 'polling/detail.html'

    def post(self, request, *args, **kwargs):
        poll = self.get_object()

        if request.POST.get("vote") == "Yes":
            poll.score += 1
        elif request.POST.get("vote") == "No":
            poll.score -= 1
        poll.save()

        context = {"object": poll}
        return render(request, "polling/detail.html", context)

blogging/templates/blogging/add.html
{% extends "base.html" %}{% block content %}

<a class="backlink" href="/">Home</a>
<h1>New Blog Post</h1>

<form method="post">
{% csrf_token %}
{{ form.as_p }}

<button type="submit" class="add_post">Submit</button>
</form>

{% endblock %}

blogging/templates/blogging/detail.html
{% extends "base.html" %}{% block content %}

<a class="backlink" href="/">Home</a>
<h1>{{ post }}</h1>
<p class="byline">
    Posted by {{ post.author.username }} &mdash; {{ post.published_date}}
</p>
<div class="post-body">
    {{ post.text }}
</div>
<ul class="categories">
    {% for category in post.categories.all %}
        <li>Categories: {{ category }}</li>
    {% endfor %}
</ul>
{% endblock %}

blogging/templates/blogging/list.html
{% extends "base.html" %}{% block content %}

    <a class="add_post" href="/add">Create Blog Post</a>
    <h1>Super Cool Blog Posts</h1>
    {% for post in post_list %}
    <div class="post">
        <h2>
            <a href="{% url 'blog_detail' post.pk %}">{{ post }}</a>
        </h2>
        <p class="byline">
            Posted by {{ post.author.username }} &mdash; {{ post.published_date}}
        </p>
        <div class="post_body">
            {{ post.text }}
        </div>
        <ul class="categories">
            {% for category in post.categories.all %}
                <li>{{ category }}</li>
                {% endfor %}
        </ul>
    </div>
    {% endfor %}
{% endblock %}

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>My Django Blog</title>
        <link type="text/css" rel="stylesheet" href="{% static 'django_blog.css' %}">
    </head>
    <body>
        <div id ="header">
            <ul id="control-bar">
                {% if user.is_authenticated %}
                {% if user.is_staff %}<li><a href="{% url 'admin:index' %}">admin</a></li>{% endif %}
                <li><a href="{% url 'logout' %}">logout</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">login</a></li>
                {% endif %}
            </ul>
        </div>
        <div id="containter">
            <div id="content">
                {% block content %}
                [ content will go here ]
                {% endblock %}
            </div>
        </div>
    </body>
</html>

mysite/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>My Blog Login</h1>
<form action="" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Log In"></p>
</form>
{% endblock %}

polling/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ object.title }}</h1>
<div class="poll-body">
    {{ object.text }}
</div>
<div class="poll-score">
    Current score: {{ object.score }}
</div>
<div class="poll_vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

polling/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
<h1>Polls</h1>
{% for poll in poll_list %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}